const HTTP = {
    DEFAULT_PORT: 3001,
    GRACEFUL_SHUTDOWN_TIMEOUT_MS: 10_000,
    JSON_BODY_SIZE_LIMIT: '100kb',
    RATE_LIMIT: {
        AUTH_MAX_REQUESTS: 10,
        AUTH_RESET_INTERVAL_MS: 15 * 60 * 1000,
        GLOBAL_MAX_REQUESTS: 100,
        GLOBAL_RESET_INTERVAL_MS: 15 * 60 * 1000,
    },
    STATUS: {
        BAD_REQUEST: 400,
        CONFLICT: 409,
        CREATED: 201,
        INTERNAL_SERVER_ERROR: 500,
        NOT_FOUND: 404,
        TOO_MANY_REQUESTS: 429,
        UNAUTHORIZED: 401,
    },
} as const;

export { HTTP };
